version: "3.7"
  services:
    whoami1:
      image: traefik/whoami
      ports: 
        - 80:80
    whoami2:
      image: traefik/whoami
      ports: 
        - 81:80
    whoami3:
      image: traefik/whoami
      ports: 
        - 82:80
    caddy:
      image: caddy:latest
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
